#!/usr/bin/env bash

# Copyright 2014, Joyent Inc. All rights reserved
# formats the secondary disk ( /dev/vdb1 )
# also refered to as the /data disk

# customers can provision this disk how they like
# by default we provision the whole disk as one partition

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

if [[ -b /dev/dsk/c4t0d0 ]]
then
  lib_smartdc_info "Creating 'data' pool on c4t0d0"
  zpool create data c4t0d0
fi
exit 0
