#!/usr/bin/env bash
#
# Copyright (c) 2014 Joyent Inc., All rights reserved.
#

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

# set system host name in this order
# 2) use Mdata hostname if set
# 3) use Mdata sdc:uuid

lib_smartdc_info "Start of $(basename $0) script"

for metadata_key in hostname sdc:uuid
do
   mdata_hostname=$($MDATA_GET_BIN "${metadata_key}" 2>>/dev/console)
   if [[ $? -eq 0 && ! -z "$mdata_hostname" ]]; then
      lib_smartdc_info "Metadata hostname set to $mdata_hostname"
      lib_smartdc_info "Setting hostname to $mdata_hostname"
      hostname -s "$mdata_hostname"
      exit 0
   fi
done
